import Head from "next/head";
import { useState } from "react";
import styles from "../styles/Home.module.css";
import Form from "../components/Form";
import Template from "../components/Template";

const initialState = {
  email: "",
  phone: "",
  role: "",
  school: "",
  experience: "",
  firstname: "",
  course: "",
  address: "",
  lastname: "",
  country: "",
  state: "",
  website: "",
  company: "",
  position: "",
  interest_1: "",
  interest_2: "",
  interest_3: "",
};
export default function Home() {
  const [userDetails, setUserDetails] = useState(initialState);
  const [showPDF, setShowPDF] = useState(false);
  const [enableInputs, setEnableInputs] = useState(false);

  const handleSubmit = async (e) => {
    e.preventDefault();
    setShowPDF(true);
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Resume Generator</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Form
          userDetails={userDetails}
          setUserDetails={setUserDetails}
          handleSubmit={handleSubmit}
          enableInputs={enableInputs}
          setEnableInputs={setEnableInputs}
        />
        <div>
          {showPDF && (
            <Template
              userDetails={userDetails}
              setShowPDF={setShowPDF}
              setUserDetails={setUserDetails}
              initialState={initialState}
            />
          )}
        </div>
      </main>
    </div>
  );
}
